language: java
sudo: required
services: 
  - docker
dist: trusty
jdk:
  - openjdk8
cache:
  directories:
    - $HOME/wso2am-micro-gw-toolkit-linux-3.1.0
    - $HOME/google-cloud-sdk
env:
  global: 
    - SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - echo $GCLOUD_SERVICE_KEY_STG | base64 --decode -i > ${HOME}/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
  - gcloud config set project api-mgw-cicd-demo
  - gcloud config set compute/zone southamerica-east1-a
  - gcloud container clusters get-credentials cluster-1	 
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"


script:
  - echo "skipping tests"
  - echo $BUILD_NUMBER

deploy:
  provider: script
  script: bash ./scripts/deploy-gcp.sh
  on:
    branch: master