openapi: 3.0.0
info:
  title: Online-Store
  description: This API contains operations related to online shopping store.
  version: v1.0.0
servers:
- url: /
security:
- default: []
paths:
  /products:
    get:
      responses:
        200:
          description: successful operation
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
        - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://test.com
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
  - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
x-wso2-production-endpoints:
  urls:
  - http://34.95.140.14/
  type: http
x-wso2-sandbox-endpoints:
  urls:
  - http://34.95.140.14/
  type: http
x-wso2-basePath: /store/v1.0.0
x-wso2-transports:
- http
- https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
