[docker]
  [docker.dockerConfig]
    enable = true
    name = "petstore"
    registry = 'fjunior87'
    tag = 'v1'
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #baseImage = 'wso2/wso2micro-gw:3.1.0'
    #enableDebug = ''
    #debugPort = ''
    #push = ''
  [docker.dockerCopyFiles]
    enable = true
    [[docker.dockerCopyFiles.files]]
        source = '/Users/francisco/soft/wso2am-micro-gw-toolkit-3.0.1/resources/conf/micro-gw.conf'
        target = '/home/ballerina/conf/micro-gw.conf'
        isBallerinaConf = true
  [kubernetes.kubernetesService]
    enable = true
    #name = ''
    #labels = ''
    serviceType = 'NodePort'
    #port = ''
  [kubernetes.kubernetesConfigMap]
    enable = true
    ballerinaConf = '/Users/francisco/soft/wso2am-micro-gw-toolkit-3.0.1/resources/conf/micro-gw.conf'
    #[[kubernetes.kubernetesConfigMap.configMaps]]
    #    name = ''
    #    mountPath = ''
    #    readOnly = false
    #    data = ['']