apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels: 
      component: myapi-microgateway
  template:
    metadata:
      labels: 
        component: myapi-microgateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9797'
    spec:
      containers:
        - name: myapi-microgateway
          image: fjunior87/myapi-mgw:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              protocol: "TCP"       
          env:
            - name: "b7a_log_level"
              value: "DEBUG"
            - name: "b7a_observability_metrics_enabled"
              value: "true"