apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  type: LoadBalancer
  selector: 
    component: myapi-microgateway
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090